# Generated by Django 4.2.7 on 2023-12-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Mangas', 'Mangas'), ('Ropa', 'Ropa'), ('Figuras', 'Figuras')], default=True, max_length=10),
        ),
    ]
